# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

image: Visual Studio 2017
shallow_clone: true

environment:
  # Encrypted passphrase used for decrypting the SSH private key
  # (which is used for deployment using SCP)
  SSHKeyfilePassphrase: "PF+BTT4Pj/J55cG2ySQKadCN7zHQSxFyFDmjvA9Brig="

  matrix:
    # 64-bit editor
    - Tools: "yes"
      Target: "release_debug"
      Arch: "x64"

    # 32-bit editor
    - Tools: "yes"
      Target: "release_debug"
      Arch: "x86"

    # 64-bit debug export templates
    - Tools: "no"
      Target: "release_debug"
      Arch: "x64"

    # 32-bit debug export templates
    - Tools: "no"
      Target: "release_debug"
      Arch: "x86"

    # 64-bit release export templates
    - Tools: "no"
      Target: "release"
      Arch: "x64"

    # 32-bit release export templates
    - Tools: "no"
      Target: "release"
      Arch: "x86"

install:
  - ps: $env:BuildDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd")
  - ps: scripts\appveyor\install.ps1

build_script:
  - ps: scripts\appveyor\build_script.ps1

after_build:
  - ps: scripts\appveyor\after_build.ps1
