# The GitHub repository is mirrored to GitLab.com, where continuous builds
# are performed and can be downloaded.
#
# https://gitlab.com/Calinou/godot-builds-ci
#
# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

stages:
  - build
  - deploy

variables:
  # The build name to use instead of "custom_build"
  # This helps people identify where the build comes from
  BUILD_NAME: calinou
  # The number of CPU threads to use for compiling Godot
  BUILD_THREADS: 1
  # SCons build flags to use for all platforms
  SCONS_FLAGS: debug_symbols=no progress=no -j$BUILD_THREADS
  # The Godot Git repository clone URL
  GODOT_REPO_URL: https://github.com/godotengine/godot.git

before_script:
  - "$CI_PROJECT_DIR/scripts/gitlab-ci/before_script.sh"
  - cd "godot/"

.artifacts: &artifacts
  paths:
    - artifacts/
  expire_in: 1 week

# Linux editor
# Built on Ubuntu 14.04 so that binaries run on old distributions as well
build:linux_editor:
  stage: build
  image: ubuntu:trusty
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_editor.sh"
  artifacts: *artifacts

# Linux export templates
# Built on Ubuntu 14.04 so that binaries run on old distributions as well
build:linux_templates:
  stage: build
  image: ubuntu:trusty
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_templates.sh"
  artifacts: *artifacts

# HTML5 (WebAssembly)
build:html5:
  stage: build
  image: fedora:28
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/html5.sh"
  artifacts: *artifacts

# Android
build:android:
  stage: build
  image: fedora:28
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/android.sh"
  artifacts: *artifacts

# Windows editor (64-bit)
build:windows_editor_64:
  stage: build
  image: fedora:28
  variables:
    # Use only 1 thread for building
    # (required to compile LTO-enabled builds successfully)
    BUILD_THREADS: 1
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_editor.sh" 64'
  artifacts: *artifacts

# Windows editor (32-bit)
build:windows_editor_32:
  stage: build
  image: fedora:28
  variables:
    # Use only 1 thread for building
    # (required to compile LTO-enabled builds successfully)
    BUILD_THREADS: 1
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_editor.sh" 32'
  artifacts: *artifacts

# Windows export templates (64-bit)
build:windows_templates_64:
  stage: build
  image: fedora:28
  variables:
    # Use only 1 thread for building
    # (required to compile LTO-enabled builds successfully)
    BUILD_THREADS: 1
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_templates.sh" 64'
  artifacts: *artifacts

# Windows export templates (32-bit)
build:windows_templates_32:
  stage: build
  image: fedora:28
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_templates.sh" 32'
  artifacts: *artifacts

# Deploys all artifacts (currently via SFTP)
deploy:
  stage: deploy
  image: fedora:28
  before_script:
    - dnf install -y openssh-clients zip
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/deploy.sh"
