# The GitHub repository is mirrored to GitLab.com, where continuous builds
# are performed and can be downloaded.
#
# https://gitlab.com/Calinou/godot-builds-ci
#
# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

# Use only one stage for simplicity's sake
stages:
  - build

variables:
  # The number of CPU threads to use for compiling Godot
  BUILD_THREADS: 3
  # SCons build flags to use for all platforms
  SCONS_FLAGS: debug_symbols=no progress=no -j$BUILD_THREADS
  # The Godot Git clone directory
  GODOT_DIR: $CI_PROJECT_DIR/godot
  # The build name to use instead of "custom_build"
  # This helps people identify where the build comes from
  BUILD_NAME: calinou

before_script:
  - "$CI_PROJECT_DIR/scripts/gitlab-ci/before_script.sh"
  - cd "godot/"

after_script:
  - "$CI_PROJECT_DIR/scripts/gitlab-ci/after_script.sh"

# Linux editor
# Built on Ubuntu 14.04 so that binaries run on old distributions as well
build:linux_editor:
  stage: build
  image: ubuntu:trusty
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_editor.sh"

# Linux export templates
# Built on Ubuntu 14.04 so that binaries run on old distributions as well
build:linux_templates:
  stage: build
  image: ubuntu:trusty
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_templates.sh"

# HTML5 (WebAssembly)
build:html5:
  stage: build
  image: fedora:27
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/html5.sh"

# Android
build:android:
  stage: build
  image: fedora:27
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/android.sh"

# Windows editor
build:windows_editor:
  stage: build
  image: fedora:27
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_editor.sh"

# Windows export templates
build:windows_templates:
  stage: build
  image: fedora:27
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_templates.sh"
