# The GitHub repository is mirrored to GitLab.com, where continuous builds
# are performed and can be downloaded.
#
# https://gitlab.com/Calinou/godot-builds-ci
#
# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

.retry: &retry
  max: 2
  when:
    - api_failure
    - runner_system_failure
    - stuck_or_timeout_failure
    - unknown_failure

.artifacts: &artifacts
  paths:
    - artifacts/
  expire_in: 1 week

stages:
  - build
  - deploy

variables:
  # The build name to use instead of "custom_build"
  # This helps people identify where the build comes from
  BUILD_NAME: calinou
  # The number of CPU threads to use for compiling Godot
  BUILD_THREADS: "1"
  # SCons build flags to use for all platforms
  SCONS_FLAGS: '("debug_symbols=no" "progress=no" "warnings=no" "werror=no" "-j$BUILD_THREADS")'
  # The Godot Git repository clone URL
  GODOT_REPO_URL: https://github.com/godotengine/godot.git
  # The Godot Git repository clone branch
  GODOT_REPO_BRANCH: master

# Building documentation has a different set of dependencies,
# so it has its own "before" script
before_script:
  - if [[ "$CI_JOB_NAME" == "build:docs" ]]; then
      "$CI_PROJECT_DIR/scripts/gitlab-ci/before_script_docs.sh";
      cd "godot-docs/";
    else
      "$CI_PROJECT_DIR/scripts/gitlab-ci/before_script.sh";
      cd "godot/";
    fi;

# Documentation in HTML format
build:docs:
  stage: build
  image: fedora:32
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/docs.sh"
  artifacts: *artifacts
  retry: *retry

# Linux editor
# Built on Ubuntu 16.04 so that binaries run on old distributions as well
build:linux_editor:
  stage: build
  image: ubuntu:16.04
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_editor.sh"
  artifacts: *artifacts
  retry: *retry

# Linux export templates (debug)
# Built on Ubuntu 16.04 so that binaries run on old distributions as well
build:linux_templates_debug:
  stage: build
  image: ubuntu:16.04
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_templates.sh debug"
  artifacts: *artifacts
  retry: *retry

# Linux export templates (release)
# Built on Ubuntu 16.04 so that binaries run on old distributions as well
build:linux_templates_release:
  stage: build
  image: ubuntu:16.04
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_templates.sh release"
  artifacts: *artifacts
  retry: *retry

# Linux headless editor (for exporting projects and automation)
# Built on Ubuntu 16.04 so that binaries run on old distributions as well
build:linux_headless:
  stage: build
  image: ubuntu:16.04
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_headless.sh"
  artifacts: *artifacts
  retry: *retry

# Linux dedicated server (for running projects)
# Built on Ubuntu 16.04 so that binaries run on old distributions as well
build:linux_server:
  stage: build
  image: ubuntu:16.04
  variables:
    DEBIAN_FRONTEND: noninteractive
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/build/linux_server.sh"
  artifacts: *artifacts
  retry: *retry

# HTML5/WebAssembly (debug)
build:html5_debug:
  stage: build
  image: fedora:32
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/html5.sh" debug'
  artifacts: *artifacts
  retry: *retry

# HTML5/WebAssembly (release)
build:html5_release:
  stage: build
  image: fedora:32
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/html5.sh" release'
  artifacts: *artifacts
  retry: *retry

# Android (debug)
build:android_debug:
  stage: build
  image: fedora:28
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/android.sh" debug'
  artifacts: *artifacts
  retry: *retry

# Android (release)
build:android_release:
  stage: build
  image: fedora:28
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/android.sh" release'
  artifacts: *artifacts
  retry: *retry

# Windows editor (64-bit)
build:windows_editor_64:
  stage: build
  image: fedora:32
  variables:
    # Use only 1 thread for building
    # (required to compile LTO-enabled builds successfully)
    BUILD_THREADS: "1"
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_editor.sh" 64'
  artifacts: *artifacts
  retry: *retry

# Windows editor (32-bit)
build:windows_editor_32:
  stage: build
  image: fedora:32
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_editor.sh" 32'
  artifacts: *artifacts
  retry: *retry

# Windows export templates (debug, 64-bit)
build:windows_templates_debug_64:
  stage: build
  image: fedora:32
  variables:
    # Use only 1 thread for building
    # (required to compile LTO-enabled builds successfully)
    BUILD_THREADS: "1"
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_templates.sh" debug 64'
  artifacts: *artifacts
  retry: *retry

# Windows export templates (debug, 32-bit)
build:windows_templates_debug_32:
  stage: build
  image: fedora:32
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_templates.sh" debug 32'
  artifacts: *artifacts
  retry: *retry

# Windows export templates (release, 64-bit)
build:windows_templates_release_64:
  stage: build
  image: fedora:32
  variables:
    # Use only 1 thread for building
    # (required to compile LTO-enabled builds successfully)
    BUILD_THREADS: "1"
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_templates.sh" release 64'
  artifacts: *artifacts
  retry: *retry

# Windows export templates (release, 32-bit)
build:windows_templates_release_32:
  stage: build
  image: fedora:32
  script:
    - '"$CI_PROJECT_DIR/scripts/gitlab-ci/build/windows_templates.sh" release 32'
  artifacts: *artifacts
  retry: *retry

# Deploys all artifacts (currently via SFTP)
deploy:
  stage: deploy
  image: fedora:32
  when: always
  only:
    - master@Calinou/godot-builds-ci
  before_script:
    - dnf install -yq openssh-clients zip
  script:
    - "$CI_PROJECT_DIR/scripts/gitlab-ci/deploy.sh"
  retry: *retry
