# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

language: cpp
os: osx
osx_image: xcode10.1

env:
  global:
    # The build name to use instead of "custom_build"
    # This helps people identify where the build comes from
    - BUILD_NAME="calinou"
    # The number of CPU threads to use for compiling Godot
    - BUILD_THREADS="3"
    # SCons build flags to use for all platforms
    - 'SCONS_FLAGS=("progress=no" "debug_symbols=no" "-j$BUILD_THREADS" "CACHE_NAME=${PLATFORM}_${TARGET}")'
    # The Godot Git repository clone URL
    - GODOT_REPO_URL="https://github.com/godotengine/godot"
    # SCons cache parameters
    - SCONS_CACHE="$HOME/.scons_cache"
    - SCONS_CACHE_LIMIT=1024

  matrix:
    - PLATFORM=osx    TARGET=editor
    - PLATFORM=osx    TARGET=templates
    - PLATFORM=iphone TARGET=templates

cache:
  directories:
    - $SCONS_CACHE

stages:
  - test
  - name: deploy
    if: branch = master

before_script:
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" != "Deploy" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/before_script.sh";
      cd "godot/";
    else
      brew update;
      brew install advancecomp;
    fi;

script:
  - if [[ "$PLATFORM" == "osx" ]] && [[ "$TARGET" == "editor" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/build/osx_editor.sh";
    fi;
  - if [[ "$PLATFORM" == "osx" ]] && [[ "$TARGET" == "templates" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/build/osx_templates.sh";
    fi;
  - if [[ "$PLATFORM" == "iphone" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/build/iphone.sh";
    fi;

after_success:
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" != "Deploy" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/after_success.sh";
    fi;

jobs:
  include:
    - stage: deploy
      script: "$TRAVIS_BUILD_DIR/scripts/travis/deploy.sh"
