# This build script is licensed under CC0 1.0 Universal:
# https://creativecommons.org/publicdomain/zero/1.0/

language: cpp

sudo: false

os:
  - osx

env:
  global:
    - OPTIONS="progress=no debug_symbols=no builtin_openssl=yes -j3"
    - GODOT_DIR="$TRAVIS_BUILD_DIR/godot"
  matrix:
    - PLATFORM=osx    TARGET=editor
    - PLATFORM=osx    TARGET=templates
    - PLATFORM=iphone TARGET=templates

before_script:
  - "$TRAVIS_BUILD_DIR/scripts/travis/before_script.sh"
  - cd "godot/"

script:
  - if [[ "$PLATFORM" = "osx" ]] && [[ "$TARGET" = "editor" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/build/osx_editor.sh";
    fi;
  - if [[ "$PLATFORM" = "osx" ]] && [[ "$TARGET" = "templates" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/build/osx_templates.sh";
    fi;
  - if [[ "$PLATFORM" = "iphone" ]]; then
      "$TRAVIS_BUILD_DIR/scripts/travis/build/iphone.sh";
    fi;

after_success:
  - "$TRAVIS_BUILD_DIR/scripts/travis/after_success.sh"
